version: '3'

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - xpack.security.enabled=false
    healthcheck:
      test: curl -fs http://localhost:9200 || exit 1
      interval: 10s
      timeout: 10s
      retries: 10

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION}
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      elasticsearch:
        condition: service_healthy

  filebeat:
    container_name: filebeat
    image: docker.elastic.co/beats/filebeat:${ELASTIC_VERSION}
    command: --strict.perms=false
    configs:
      - source: filebeat
        target: /usr/share/filebeat/filebeat.yml
    depends_on:
      elasticsearch:
        condition: service_healthy

  vault:
    container_name: vault
    image: hashicorp/vault:${VAULT_VERSION}
    command: server -config=/vault/vault.hcl
    cap_add:
      - IPC_LOCK
    ports:
      - 8200:8200
    volumes:
      - vault:/vault/file
    configs:
      - source: vault
        target: /vault/vault.hcl
    depends_on:
      - filebeat

configs:
  filebeat:
    file: ./configs/filebeat.yml
  vault:
    file: ./configs/vault.hcl

volumes:
  elasticsearch:
    driver: local
  vault:
    driver: local
