setup.template:
  name: "vault-audit"
  pattern: "vault-audit"

filebeat.inputs:
  - type: tcp
    host: "0.0.0.0:9090"

processors:
  - decode_json_fields:
      fields: ["message"]
      target: "message"
      overwrite_keys: true
      add_error_key: true
  - drop_event:
      when:
        has_fields: ["error.message"]

output.elasticsearch:
  index: "vault-audit"
  hosts: ["http://elasticsearch:9200"]
